spring:
  application:
    name: ms-warehouse
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ms_warehouse
    username: root
    password: 12345678